trigger:
- manual

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

pool:
  vmImage: 'windows-latest'

steps:

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
    
# Build the application
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Veracode Static scan C# API wrapper
- task: PowerShell@2
  displayName: Veracode Static Analysis
  inputs:
      # Download the C# API Wrapper
      # Unzip and run it against your API credetials
    targetType: 'inline'
    script: |
      Invoke-WebRequest -Uri https://tools.veracode.com/integrations/API-Wrappers/CSharp/bin/VeracodeCSharpAPI.zip -OutFile $(System.DefaultWorkingDirectory)\VeracodeCSharpAPI.zip
      Expand-Archive -Path $(System.DefaultWorkingDirectory)\VeracodeCSharpAPI.zip -DestinationPath $(System.DefaultWorkingDirectory)\VeracodeCSharpAPI -Force 
      Move-Item -Path (Join-Path $(System.DefaultWorkingDirectory)\VeracodeCSharpAPI "VeracodeC#API.exe") -Destination $(System.DefaultWorkingDirectory)\VeracodeC#API.exe -Force
      $(System.DefaultWorkingDirectory)\VeracodeCSharpAPI\VeracodeC#API.exe -action UploadAndScan -vid $(VERACODE_API_ID) -vkey $(VERACODE_API_KEY) -deleteincompletescan 1 -createprofile false -appname "Verademo-dotnet" -sandboxname "Azure DevOps" -version "$(build.buildNumber)" -filepath $(build.artifactStagingDirectory)\Verademo-dotnet.zip